2025-09-11 17:25:00,579 INFO    MainThread:96205 [wandb_setup.py:_flush():80] Current SDK version is 0.21.1
2025-09-11 17:25:00,579 INFO    MainThread:96205 [wandb_setup.py:_flush():80] Configure stats pid to 96205
2025-09-11 17:25:00,579 INFO    MainThread:96205 [wandb_setup.py:_flush():80] Loading settings from /Users/leo/.config/wandb/settings
2025-09-11 17:25:00,579 INFO    MainThread:96205 [wandb_setup.py:_flush():80] Loading settings from /Users/leo/Desktop/AML/Multi-GNN/wandb/settings
2025-09-11 17:25:00,579 INFO    MainThread:96205 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-09-11 17:25:00,579 INFO    MainThread:96205 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /Users/leo/Desktop/AML/Multi-GNN/wandb/run-20250911_172500-h9a8ju8h/logs/debug.log
2025-09-11 17:25:00,579 INFO    MainThread:96205 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /Users/leo/Desktop/AML/Multi-GNN/wandb/run-20250911_172500-h9a8ju8h/logs/debug-internal.log
2025-09-11 17:25:00,579 INFO    MainThread:96205 [wandb_init.py:init():830] calling init triggers
2025-09-11 17:25:00,579 INFO    MainThread:96205 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'epochs': 100, 'batch_size': 8192, 'model': 'gin', 'data': 'data', 'num_neighbors': [100, 100], 'lr': 0.006213266113989207, 'n_hidden': 66.00315515631006, 'n_gnn_layers': 2, 'loss': 'ce', 'w_ce1': 1.0000182882773443, 'w_ce2': 6.275014431494497, 'dropout': 0.00983468338330501, 'final_dropout': 0.10527690625126304, 'n_heads': None, '_wandb': {}}
2025-09-11 17:25:00,579 INFO    MainThread:96205 [wandb_init.py:init():871] starting backend
2025-09-11 17:25:00,810 INFO    MainThread:96205 [wandb_init.py:init():874] sending inform_init request
2025-09-11 17:25:00,878 INFO    MainThread:96205 [wandb_init.py:init():882] backend started and connected
2025-09-11 17:25:00,882 INFO    MainThread:96205 [wandb_init.py:init():953] updated telemetry
2025-09-11 17:25:00,911 INFO    MainThread:96205 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-09-11 17:25:01,913 INFO    MainThread:96205 [wandb_init.py:init():1029] starting run threads in backend
2025-09-11 17:25:02,015 INFO    MainThread:96205 [wandb_run.py:_console_start():2494] atexit reg
2025-09-11 17:25:02,015 INFO    MainThread:96205 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-09-11 17:25:02,015 INFO    MainThread:96205 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-09-11 17:25:02,015 INFO    MainThread:96205 [wandb_run.py:_redirect():2434] Redirects installed.
2025-09-11 17:25:02,017 INFO    MainThread:96205 [wandb_init.py:init():1075] run started, returning control to user process
2025-09-11 17:31:16,161 INFO    MsgRouterThr:96205 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-09-11 17:31:16,926 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,936 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,937 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,939 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,939 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,940 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,940 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,941 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,941 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,942 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,942 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,943 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,943 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,943 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,944 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,944 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-09-11 17:31:16,944 ERROR   MainThread:96205 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/leo/miniconda3/envs/multignn/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
